### ISSUE TITLE
How to run this example

### ISSUE THREAD

**Issue by eledger** [jpayne23/Car-Lease-Demo-test#2]
Hello,
This is absolutely wonderful stuff , but can you please add some build and deployment instructions?
Is it ready to be built and deployed to bluemix or to be run in conjunction with local hyperledger setup?

thanks

**Comment by eledger** [comment]
Never mind. Please feel free to close it. I used marbles demo hyperledger port example.
Now I can run it in local setup with hyperledger. You might want to put a link here.
I couldnt quite work out an easy integration of users needed on membersvc but should figure out on my own..

**Comment by bd37** [comment]
Hello, I'm receiving the following error with:
/root/car-lease-demo/node_modules/require-reload/reload.js:16
        throw e;
SyntaxError: Unexpected token u in JSON at position 0

and I updated mycred.json with following

{
  "credentials": {
    "peers": [
      {
        "discovery_host": "127.0.0.1",
        "discovery_port": 30303,
        "api_host": "127.0.0.1",
        "api_port_tls": 5000,
        "api_port": 5000,
        "type": "peer",
        "network_id": "vp0",
        "container_id": "con_vp0",
        "id": "dev_vp0",
        "api_url": "http://127.0.0.1:5000"
      }
       ],
    "ca": {
      "catest": {
        "url": "grpc://127.0.0.1:50051",
        "discovery_host": "127.0.0.1",
        "discovery_port": 50051,
        "api_host": "127.0.0.1",
        "api_port_tls": 50051,
        "api_port": 50051,
        "type": "ca",
        "network_id": "net_ca",
        "container_id": "con_vp0"
      }
    },

I'd like to get your completion efforts. Thanks

**Comment by eledger** [comment]
bd37  Can you run your json in a validator to make sure it has no special characters?
I think it seems it has some special characters which can not be parsed.
Try this link if your json is well formed.
https://jsonformatter.curiousconcept.com/

may be remove any special characters and try? I can attach my mycred file and you can try with that if it helps?

**Comment by bd37** [comment]
Thanks eledger, Can I get your mycred file because I'll try with your file? How can I get your mycred file?   Did you succeed in local? I succeeded marbles and cp-web. Thanks a lot!

**Comment by bd37** [comment]
Thanks eledger, Can I get your mycred file because I'm spending a lot of time about that? How can I get from you? I succeeded marbels and cp-web in local. Thanks a lot!

**Comment by eledger** [comment]
Seems slike an attachment of .json format is not supported. I am on archana@everledger.io.. if you drop an email wills end it across.

**Comment by jpayne23** [comment]
Hi eledger, apologies for the delayed response. Thank you for the feedback, we will definitely add some information on this shortly.

Also note that this repository is no longer used, the new repository is now located at https://github.com/IBM-Blockchain/car-lease-demo so you will be able to get the latest demo from there and will be where all changes are added.

Currently the demo works on bluemix with the blockchain service so to deploy it simply click the "Deploy to Bluemix" button (this does require a bluemix account). We will be working on updating the demo to allow you to run it locally as well, but unfortunately this isn't there yet.

We will keep you updated on when this will be available.

Thanks

**Comment by eledger** [comment]
Thanks for this.. works for me
